/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.daqecho.ftsi_analytics.ui;

/**
 *
 * @author oilfi
 */
public class NewChartEditorAxis extends javax.swing.JFrame
{

    /**
     * Creates new form NewChartEditorAxis
     */
    public NewChartEditorAxis()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        ChartEditor_Properties_Jlabel = new javax.swing.JLabel();
        ChartEditor_Suggestions_Jlabel = new javax.swing.JLabel();
        ChartEditor_Title_Jlabel1 = new javax.swing.JLabel();
        NewChartEditorProperties_TitleEdit_JTextField = new javax.swing.JTextField();
        ChartEditor_Title_Jlabel2 = new javax.swing.JLabel();
        NewChartEditorProperties_Top_jSeparator = new javax.swing.JSeparator();
        NewChartEditorProperties_DVT_Jlabel2 = new javax.swing.JLabel();
        NewChartEditorProperties_DVT_Jlabel4 = new javax.swing.JLabel();
        NewChartEditorProperties_Bottom_jseperator = new javax.swing.JSeparator();
        NewChartEditorProperties_UseAutomaticGridLines_JCheckBox = new javax.swing.JCheckBox();
        NewChartEditorProperties_GLEL_Jlabel = new javax.swing.JLabel();
        NewChartEditorProperties_GridLinesEverys_JTextField = new javax.swing.JTextField();
        NewChartEditorProperties_GLEU_Jlabel5 = new javax.swing.JLabel();
        ChartEditor_TMEL_Jlabel = new javax.swing.JLabel();
        NewChartEditorProperties_TickMarksEvery_JTextField = new javax.swing.JTextField();
        ChartEditor_TMEU_Jlabel = new javax.swing.JLabel();
        NewChartEditorProperties_Back_JButton = new javax.swing.JButton();
        NewChartEditorProperties_Next_JButton = new javax.swing.JButton();
        NewChartEditorProperties_Finish_JButton = new javax.swing.JButton();
        NewChartEditorProperties_Cancel_JButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        ChartEditor_TMEU_Jlabel1 = new javax.swing.JLabel();
        ChartEditor_TMEU_Jlabel2 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setRequestFocusEnabled(false);

        ChartEditor_Properties_Jlabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ChartEditor_Properties_Jlabel.setText("Chart Properties");

        ChartEditor_Suggestions_Jlabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChartEditor_Suggestions_Jlabel.setText("Select properties for the line chart.");

        ChartEditor_Title_Jlabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChartEditor_Title_Jlabel1.setText("Title:");

        NewChartEditorProperties_TitleEdit_JTextField.setText("Title");
        NewChartEditorProperties_TitleEdit_JTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                NewChartEditorProperties_TitleEdit_JTextFieldActionPerformed(evt);
            }
        });

        ChartEditor_Title_Jlabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChartEditor_Title_Jlabel2.setText("Types and Units:");

        NewChartEditorProperties_DVT_Jlabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NewChartEditorProperties_DVT_Jlabel2.setText("Channels:");

        NewChartEditorProperties_DVT_Jlabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NewChartEditorProperties_DVT_Jlabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewChartEditorProperties_DVT_Jlabel4.setText("to");
        NewChartEditorProperties_DVT_Jlabel4.setToolTipText("");

        NewChartEditorProperties_UseAutomaticGridLines_JCheckBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NewChartEditorProperties_UseAutomaticGridLines_JCheckBox.setSelected(true);
        NewChartEditorProperties_UseAutomaticGridLines_JCheckBox.setText("Use Automatic Grid Lines");

        NewChartEditorProperties_GLEL_Jlabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NewChartEditorProperties_GLEL_Jlabel.setText("Grid lines every:");

        NewChartEditorProperties_GridLinesEverys_JTextField.setText("0.0");

        NewChartEditorProperties_GLEU_Jlabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NewChartEditorProperties_GLEU_Jlabel5.setText("Line Style: ");

        ChartEditor_TMEL_Jlabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChartEditor_TMEL_Jlabel.setText("Tick marks every:");

        NewChartEditorProperties_TickMarksEvery_JTextField.setText("0.0");

        ChartEditor_TMEU_Jlabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChartEditor_TMEU_Jlabel.setText("s");

        NewChartEditorProperties_Back_JButton.setText("< Back");

        NewChartEditorProperties_Next_JButton.setText("Next >");

        NewChartEditorProperties_Finish_JButton.setText("Finish");

        NewChartEditorProperties_Cancel_JButton.setText("Cancel");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jRadioButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton1.setText("Solid");

        jRadioButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton2.setText("Dashed");

        jRadioButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton3.setText("Dotted");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Color");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setOpaque(false);

        jCheckBox1.setText("jCheckBox1");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField1");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        ChartEditor_TMEU_Jlabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChartEditor_TMEU_Jlabel1.setText("s");

        ChartEditor_TMEU_Jlabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChartEditor_TMEU_Jlabel2.setText("s");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ChartEditor_Suggestions_Jlabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChartEditor_Properties_Jlabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ChartEditor_Title_Jlabel2)
                                        .addComponent(ChartEditor_Title_Jlabel1))
                                    .addGap(72, 72, 72)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(NewChartEditorProperties_TitleEdit_JTextField)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(NewChartEditorProperties_DVT_Jlabel2)
                                        .addComponent(NewChartEditorProperties_GLEU_Jlabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(111, 111, 111)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jCheckBox1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(NewChartEditorProperties_DVT_Jlabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(ChartEditor_TMEU_Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(13, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NewChartEditorProperties_UseAutomaticGridLines_JCheckBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NewChartEditorProperties_Back_JButton)
                                .addGap(18, 18, 18)
                                .addComponent(NewChartEditorProperties_Next_JButton)
                                .addGap(18, 18, 18)
                                .addComponent(NewChartEditorProperties_Finish_JButton)
                                .addGap(18, 18, 18)
                                .addComponent(NewChartEditorProperties_Cancel_JButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewChartEditorProperties_GLEL_Jlabel)
                                    .addComponent(ChartEditor_TMEL_Jlabel))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NewChartEditorProperties_TickMarksEvery_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                                    .addComponent(NewChartEditorProperties_GridLinesEverys_JTextField))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChartEditor_TMEU_Jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChartEditor_TMEU_Jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 488, Short.MAX_VALUE)
                    .addComponent(NewChartEditorProperties_Top_jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 482, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 488, Short.MAX_VALUE)
                    .addComponent(NewChartEditorProperties_Bottom_jseperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 482, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ChartEditor_Properties_Jlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChartEditor_Suggestions_Jlabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewChartEditorProperties_TitleEdit_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChartEditor_Title_Jlabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChartEditor_Title_Jlabel2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(NewChartEditorProperties_DVT_Jlabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewChartEditorProperties_GLEU_Jlabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewChartEditorProperties_DVT_Jlabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChartEditor_TMEU_Jlabel))
                        .addGap(18, 18, 18)
                        .addComponent(NewChartEditorProperties_UseAutomaticGridLines_JCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewChartEditorProperties_GLEL_Jlabel)
                    .addComponent(NewChartEditorProperties_TickMarksEvery_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChartEditor_TMEU_Jlabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChartEditor_TMEL_Jlabel)
                    .addComponent(NewChartEditorProperties_GridLinesEverys_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChartEditor_TMEU_Jlabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewChartEditorProperties_Cancel_JButton)
                    .addComponent(NewChartEditorProperties_Next_JButton)
                    .addComponent(NewChartEditorProperties_Back_JButton)
                    .addComponent(NewChartEditorProperties_Finish_JButton))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 459, Short.MAX_VALUE)
                    .addComponent(NewChartEditorProperties_Top_jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 459, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 459, Short.MAX_VALUE)
                    .addComponent(NewChartEditorProperties_Bottom_jseperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 459, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewChartEditorProperties_TitleEdit_JTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_NewChartEditorProperties_TitleEdit_JTextFieldActionPerformed
    {//GEN-HEADEREND:event_NewChartEditorProperties_TitleEdit_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewChartEditorProperties_TitleEdit_JTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
            {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
                {
                if ( "Nimbus".equals(info.getName()) )
                    {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    }
                }
            } catch ( ClassNotFoundException ex )
            {
            java.util.logging.Logger.getLogger(NewChartEditorAxis.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
            } catch ( InstantiationException ex )
            {
            java.util.logging.Logger.getLogger(NewChartEditorAxis.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
            } catch ( IllegalAccessException ex )
            {
            java.util.logging.Logger.getLogger(NewChartEditorAxis.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
            } catch ( javax.swing.UnsupportedLookAndFeelException ex )
            {
            java.util.logging.Logger.getLogger(NewChartEditorAxis.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
            }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new NewChartEditorAxis().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChartEditor_Properties_Jlabel;
    private javax.swing.JLabel ChartEditor_Suggestions_Jlabel;
    private javax.swing.JLabel ChartEditor_TMEL_Jlabel;
    private javax.swing.JLabel ChartEditor_TMEU_Jlabel;
    private javax.swing.JLabel ChartEditor_TMEU_Jlabel1;
    private javax.swing.JLabel ChartEditor_TMEU_Jlabel2;
    private javax.swing.JLabel ChartEditor_Title_Jlabel1;
    private javax.swing.JLabel ChartEditor_Title_Jlabel2;
    private javax.swing.JButton NewChartEditorProperties_Back_JButton;
    private javax.swing.JSeparator NewChartEditorProperties_Bottom_jseperator;
    private javax.swing.JButton NewChartEditorProperties_Cancel_JButton;
    private javax.swing.JLabel NewChartEditorProperties_DVT_Jlabel2;
    private javax.swing.JLabel NewChartEditorProperties_DVT_Jlabel4;
    private javax.swing.JButton NewChartEditorProperties_Finish_JButton;
    private javax.swing.JLabel NewChartEditorProperties_GLEL_Jlabel;
    private javax.swing.JLabel NewChartEditorProperties_GLEU_Jlabel5;
    private javax.swing.JTextField NewChartEditorProperties_GridLinesEverys_JTextField;
    private javax.swing.JButton NewChartEditorProperties_Next_JButton;
    private javax.swing.JTextField NewChartEditorProperties_TickMarksEvery_JTextField;
    private javax.swing.JTextField NewChartEditorProperties_TitleEdit_JTextField;
    private javax.swing.JSeparator NewChartEditorProperties_Top_jSeparator;
    private javax.swing.JCheckBox NewChartEditorProperties_UseAutomaticGridLines_JCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
